version: '3'
services:  
  mysql:
    image: "mysql:5.7"
    container_name: "sz-mysql5.7"
    volumes:
      - ./mysql5.7/my.cnf:/etc/mysql/my.cnf
      - ./mysql5.7/data:/var/lib/mysql
      - ./mysql5.7/log/mysql/error.log:/var/log/mysql/error.log
    ports:
      - "33060:3306"   
    environment:                        # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MYSQL_ROOT_PASSWORD: password         # 设置root用户密码
      MYSQL_DATABASE: test              # 初始化的数据库名称      
    restart: always
      
