version: '3'
services:     
  nginx:
    image: "nginx"
    container_name: "sz-nginx"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/log:/var/log/nginx
      - ./nginx/www:/var/www
    environment:                        # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    ports:
      - "80:80"               #先确定机器上有没有其他nginx在占用这个端口
      - "443:443"     
    restart: always
    
