version: '3'
services:      
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "sz-rabbitmq"
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=123456
    volumes:
      - ./data:/var/lib/rabbitmq
